version: '3'

volumes:
  node_modules:

services:
  node-ch-dev:
    container_name: node-challenges
    restart: unless-stopped
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    volumes:
      - .:/app 
      - node_modules:/app/node_modules/
    networks:
      - node-ch-network
networks:
  node-ch-network:
    driver: bridge

